services:
    palabre_user.registration.form.type:
        class: Palabre\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: palabre_user_registration }
    palabre_user.profile.form.type:
        class: Palabre\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: palabre_user_profile }