parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: palabre
    database_user: root
    database_password: 01dec2007
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c4b1f6102fb73b4b6b4795c7965e341bf
    database_path: null
