palabre_project_project_new:
    pattern:   /new
    defaults:  { _controller: PalabreProjectBundle:Project:create }

palabre_project_project_create:
    pattern:   /create
    defaults:  { _controller: PalabreProjectBundle:Project:create }
    requirements:
        _method:  POST
        
palabre_project_project_edit:
    pattern:   /edit/{id}
    defaults:  { _controller: PalabreProjectBundle:Project:update }
    
palabre_project_project_update:
    pattern:   /update/{id}
    defaults:  { _controller: PalabreProjectBundle:Project:update }
    requirements:
        _method:  POST
        
palabre_project_projects:
    pattern:   /
    defaults:  { _controller: PalabreProjectBundle:Project:index }
    
palabre_project_project_delete:
    pattern:   /delete/{id}
    defaults:  { _controller: PalabreProjectBundle:Project:delete }