palabre_user_list:
    pattern:   /list/{page}
    defaults:  { _controller: PalabreUserBundle:User:list, page: 1 }
palabre_user_edit:
    pattern:   /edit/{id}
    defaults:  { _controller: PalabreUserBundle:User:edit }
palabre_user_delete:
    pattern:   /delete/{id}
    defaults:  { _controller: PalabreUserBundle:User:delete }