palabre_user_list:
    pattern:   /list/{tri}/{page}
    defaults:  { _controller: PalabreUserBundle:User:list, tri: 'lastName', page: 1 }
palabre_user_create:
    pattern:   /create/
    defaults:  { _controller: PalabreUserBundle:User:create }
palabre_user_edit:
    pattern:   /edit/{id}
    defaults:  { _controller: PalabreUserBundle:User:edit }
palabre_user_delete:
    pattern:   /delete/{id}
    defaults:  { _controller: PalabreUserBundle:User:delete }